---
title: "ProcessEEG Figure Code"
output: html_document
date: "2025-09-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
posterColours <- c("#333E47", "#6a757c", "#e31936")

condition <- 6
theIDX <- which(stimulusConditions == condition, arr.ind = TRUE)
conditionEEGTemp <- matrix(NA,nrow=10000,ncol =12)
conditionFFTTemp <- matrix(NA,nrow=10000,ncol =12)

for (rep in 1:12){
  conditionEEGTemp[,rep] <- eAvgEEGData[,theIDX[rep,1], theIDX[rep,2]]
  conditionFFTTemp[,rep] <- eAvgFFTData[,theIDX[rep,1], theIDX[rep,2]]
}

tempxy <- data.frame(Re(conditionFFTTemp[31,]),Im(conditionFFTTemp[31,]))
D <- sqrt(mahalanobis(tempxy,colMeans(tempxy),cov(tempxy)))
outIDX <- which(D < 3)
conditionFFT <- conditionFFTTemp[ ,outIDX]
conditionEEG <- conditionEEGTemp[ ,outIDX]

binoc <- apply(abs(conditionFFT), 1, mean)
binocEEG <- apply(conditionEEG, 1, mean)
binocEEG[1:1000] <- binocEEG[1:1000] - mean(binocEEG[1:1000])


# png("~/Library/CloudStorage/Box-Box/Binocularity Noise/Paper_test/Figures/EEG.png", width = 6.5, height = 3.5, res = 300,units = "in", bg = "transparent")
yLimit <- range(pretty(range(pretty(range(binocEEG[1:1000])))))
plot(x = NULL, y = NULL, xlim = c(0,1000), ylim = yLimit, axes = FALSE, ann = FALSE)
axis(1, at = pretty(c(0,1000)), tck = -.015, lwd = 2, labels = FALSE)
axis(2, at = pretty(yLimit), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(c(0,1000)),1, at = pretty(c(0,1000)), line = .4)
mtext(pretty(yLimit), 2, at = pretty(yLimit), line = .4, las = 1)
abline(h = 0, lwd = 2, col = "gray75")
lines(1:1000, binocEEG[1:1000], lwd = 2, col = posterColours[1])
mtext("Time (ms)", 1, font = 2, line = 1.5)
mtext(bquote(bold("Electrical Potential ("*mu*"V)")), 2, font = 2, line = 2)
lines(1:1000, Real(tes[1:1000])/1000, col = "red")
# dev.off()

png("~/Library/CloudStorage/Box-Box/Binocularity Noise/Paper_test/Figures/SSVEPAmp.png", width = 8, height = 5, res = 300,units = "in", bg = "transparent")
yLimit <- c(0,1)
plot(x = NULL, y = NULL, xlim = c(0,100), ylim = yLimit, axes = FALSE, ann = FALSE)
axis(1, at = pretty(c(0,100)), tck = -.015, lwd = 2, labels = FALSE)
axis(2, at = pretty(yLimit), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(c(0,100))/10,1, at = pretty(c(0,100)), line = .4)
mtext(pretty(yLimit), 2, at = pretty(yLimit), line = .4, las = 1)
abline(v = c(30, 60,90), lwd = 2, col = "gray75")
text(c(31,61,91), 2.5, c("3Hz", "6Hz", "9Hz"), adj = 0)
lines(1:100, binoc[2:101], lwd = 2, col = posterColours[1])
mtext("Frequency (Hz)", 1, font = 2, line = 1.5)
mtext(bquote(bold("SSVEP Amplitude ("*mu*"V)")), 2, font = 2, line = 2)
dev.off()
```



```{r}
condition <- 5
theIDX <- which(stimulusConditions == condition, arr.ind = TRUE)
conditionEEGTemp <- matrix(NA,nrow=10000,ncol =12)
conditionFFTTemp <- matrix(NA,nrow=10000,ncol =12)

for (rep in 1:12){
  conditionEEGTemp[,rep] <- eAvgEEGData[,theIDX[rep,1], theIDX[rep,2]]
  conditionFFTTemp[,rep] <- eAvgFFTData[,theIDX[rep,1], theIDX[rep,2]]
}

tempxy <- data.frame(Re(conditionFFTTemp[31,]),Im(conditionFFTTemp[31,]))
D <- sqrt(mahalanobis(tempxy,colMeans(tempxy),cov(tempxy)))
outIDX <- which(D < 3)
conditionFFT <- conditionFFTTemp[ ,outIDX]
conditionEEG <- conditionEEGTemp[ ,outIDX]

antiphase <- apply(abs(conditionFFT), 1, mean)
plot(antiphase[2:100])
```

```{r, fig.width=8}
coloursT <- add.alpha(colours)

yLimit <- c(-40,40)
xLimit <- c(0,1000)
# png("~/Library/CloudStorage/Box-Box/Binocularity Noise/Paper/Figures/ElectrodePotential.png", width = 9.5, height = 5.5, res = 300, units = "in", bg = "transparent")
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
axis(1, at = pretty(xLimit), tck = -.015, lwd = 2, labels = FALSE, pos = 0)
axis(1, at = pretty(xLimit), tck = .015, lwd = 2, labels = FALSE, pos = 0)
axis(2, at =  pretty(yLimit), tck = -.015, lwd = 2, labels = FALSE,)
mtext(pretty(yLimit), 2, at = pretty(yLimit), las = 1, line = .5)
text(pretty(xLimit), -7, pretty(xLimit))
text(1000, -40, "Time (ms)", font = 1, adj = 1)
mtext(bquote("Electrical Potential"~" ("~mu~"V)"), 2, line = 2, adj = 0.5)

lines(eData[1,3000:4000,theIDX[2,1], theIDX[2,2]]-mean(eData[1,,theIDX[2,1], theIDX[2,2]]), lwd = 2, col = coloursT[4])
lines(eData[2,3000:4000,theIDX[2,1], theIDX[2,2]]-mean(eData[2,,theIDX[2,1], theIDX[2,2]]), lwd = 2, col = coloursT[3])
lines(eData[3,3000:4000,theIDX[2,1], theIDX[2,2]]-mean(eData[3,,theIDX[2,1], theIDX[2,2]]), lwd = 2, col = coloursT[2])
lines(eData[4,3000:4000,theIDX[2,1], theIDX[2,2]]-mean(eData[4,,theIDX[2,1], theIDX[2,2]]), lwd = 2, col = coloursT[1])
legend("topleft", legend = theChannels, lwd = 2, col = coloursT[4:1], bty = "n", cex = .8)
# dev.off()
```

```{r}
yLimit <- c(0,3)
xLimit <- c(0,100)
# png("~/Library/CloudStorage/Box-Box/Binocularity Noise/Paper/Figures/FFTSNR.png", width = 9, height = 3, res = 300, units = "in", bg = "transparent")

par(mfrow = c(1,2), mai = c(.2,.6,0,.25), omi = c(.4,.1,.05,.05))
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
axis(1, at = pretty(xLimit)+1, tck = -.015, lwd = 2, labels = FALSE)
axis(2, at =  pretty(yLimit), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(yLimit),2,at = pretty(yLimit), line = .4, las = 1)
mtext(pretty(xLimit)/10,1,at = pretty(xLimit)+1, line = .4, las = 1)
mtext("Frequency (Hz)", 1, font = 1, line = 1.5)
mtext(bquote("Amplitude"~" ("~mu~"V)"), 2, line = 2)
rect(31-5,0,31+5,3, col = coloursT[5], border = NA)
rect(61-5,0,61+5,3, col = coloursT[5], border = NA)
rect(91-5,0,91+5,3, col = coloursT[5], border = NA)
abline(v = c(31, 61, 91), lty = 2, col = colours[5])

lines(2:100, abs(eAvgFFTData[2:100,theIDX[2,1], theIDX[2,2]]),col = colours[6], lwd = 2)
text(c(32,62,92), 3.05, paste0(c(3,6,9), "Hz"), adj = 0, cex = .8)

yLimit <- c(1,4)
xLimit <- c(0,100)
plot(x = NULL, y = NULL, xlim = xLimit, ylim = yLimit, axes = FALSE, ann = FALSE)
axis(1, at = pretty(xLimit)+1, tck = -.015, lwd = 2, labels = FALSE)
axis(2, at =  pretty(yLimit), tck = -.015, lwd = 2, labels = FALSE)
mtext(pretty(yLimit),2,at = pretty(yLimit), line = .4, las = 1)
mtext(pretty(xLimit)/10,1,at = pretty(xLimit)+1, line = .4, las = 1)
mtext("Frequency (Hz)", 1, font = 1, line = 1.5)
mtext("SNR", 2, line = 2.5)
abline(v = c(31, 61, 91), lty = 2, col = colours[5])
text(c(32,62,92), 4.05, paste0(c(3,6,9), "Hz"), adj = 0, cex = .8)

lines(2:100, avgSNRCondition[2:100,6],col = colours[6], lwd = 2)
# dev.off()
```

```{r, fig.width=15}
xLim = c(0,200)
theCond <- matrix(c(1,2,3,13,NA, 4:12, NA), nrow = 3, ncol = 5, byrow = TRUE)
par(mfrow = c(3,5), mai = c(.2,.2,.2,.1),omi = c(.25,.25,.25,.25))
yLim <- c(1,max(range(pretty(range(avgSNRCondition)))))
for (II in 1:3){
  for (C in theCond[II,]){
    plot(x = NULL, y = NULL, xlim = xLim, ylim = yLim, axes = FALSE, ann = FALSE)
    if (!is.na(C)){
      axis(2, at = pretty(yLim), lwd = 2, tck = -.015, labels = FALSE)
      
      if (II == 3){
        mtext(pretty(xLim)/10, 1, at = pretty(xLim), line = .3)
        mtext("Frequency (Hz)", 1, font = 2, line = 1.5)
      }
      if (C == 1 | C == 4 | C == 9){
        mtext(pretty(yLim), 2, at = pretty(yLim), line = .3, las = 1)
        mtext("SNR", 2, font = 2, line = 2)
      }
      
      abline(v = 31, lty = 2, col = colours[3], lwd = 2)
      abline(v = 61, lty = 2, col = colours[3], lwd = 2)
      abline(v = 91, lty = 2, col = colours[3], lwd = 2)
      abline(v = 121, lty = 2, col = colours[3], lwd = 2)
      abline(v = 151, lty = 2, col = colours[3], lwd = 2)
      abline(v = 181, lty = 2, col = colours[3], lwd = 2)
      
      text(31.5, 6, "3Hz", adj = 0)
      text(61.5, 6, "6Hz", adj = 0)
      text(91.5, 6, "9Hz", adj = 0)
      text(121.5,6, "12Hz", adj = 0)
      text(151.5,6, "15Hz", adj = 0)
      text(181.5,6, "18Hz", adj = 0)
      
      lines(1:200, avgSNRCondition[,C], lwd = 4, col = colours[1])
      mtext(paste0("Condition ", C), 3, line = 0, adj = 0)
      axis(1, at = pretty(xLim), lwd = 2, tck = -.015, labels = FALSE)
    }
  }
}
```













